version: '3.8'

services:
  example-frontend:
    image: example-frontend
#    build: ./example-frontend
    ports:
      - 4999:4999
  example-backend:
    image: example-backend
#    build: ./example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis 
